import os
import time

start_time = time.time()
# os.system('python3 comparer_runner.py boats.mp4 cvat --available_classes boat')
# os.system('python3 comparer_runner.py highway.mp4 cvat --available_classes car')
# os.system('python3 comparer_runner.py pitbull.mp4 cvat --available_classes dog person bicycle handbag')
# os.system('python3 comparer_runner.py street.mp4 cvat --available_classes person bus car bicycle motorcycle truck')
# os.system('python3 comparer_runner.py street2.mp4 cvat --available_classes person bus car bicycle motorcycle truck')
# os.system('python3 comparer_runner.py birds3.mp4 cvat --available_classes bird')
# os.system('python3 comparer_runner.py birds3.mp4 cvat --available_classes person')
# os.system('python3 comparer_runner.py bench.mp4 cvat --available_classes person car bicycle apple bench handbag umbrella parking_meter')
# os.system('python3 comparer_runner.py park.mp4 cvat --available_classes person dog bicycle bench')
# os.system('python3 comparer_runner.py park2.mp4 cvat --available_classes person dog bicycle backpack bench')
# os.system('python3 comparer_runner.py bike.mp4 cvat --available_classes person bicycle')
# os.system('python3 comparer_runner.py gdynia.mp4 cvat --available_classes person car bicycle apple bench handbag umbrella boat chair')
# os.system('python3 comparer_runner.py gdynia2.mp4 cvat --available_classes person car bicycle apple bench handbag umbrella boat chair')
# os.system('python3 comparer_runner.py gdynia3.mp4 cvat --available_classes person car bicycle apple bench handbag umbrella boat chair')
# os.system('python3 main.py bike bike --available_classes bicycle person')
# os.system('python3 main.py bike2 bike2 --available_classes bicycle person')
# os.system('python3 main.py bike3 bike3 --available_classes bicycle person')
# os.system('python3 main.py bike4 bike4 --available_classes bicycle person')
# os.system('python3 main.py bike5 bike5 --available_classes bicycle person')
# os.system('python3 main.py bike6 bike6 --available_classes bicycle person')
# os.system('python3 main.py pitbull pitbull --available_classes dog person bicycle handbag')
os.system('python3 comparer_runner.py car.mp4 cvat --available_classes car truck person bus')
os.system('python3 comparer_runner.py cars2.mp4 cvat --available_classes car truck person bus')
os.system('python3 comparer_runner.py cars3.mp4 cvat --available_classes car truck person bus')
# os.system('python3 main.py bike3 bike3 --available_classes bicycle person')
# os.system('python3 main.py bike4 bike4 --available_classes bicycle person')
# os.system('python3 main.py bike5 bike5 --available_classes bicycle person')
# os.system('python3 main.py bike6 bike6 --available_classes bicycle person')
e = int(time.time() - start_time)
print('WHOLE TIME: ' + '{:02d}:{:02d}:{:02d}'.format(e // 3600, (e % 3600 // 60), e % 60))